apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  burst: 100
  kubeconfig: /Users/funky/Downloads/tke-edge
  qps: 50
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: scheduling-framework-example
  resourceNamespace: kube-system
  retryPeriod: 2s
percentageOfNodesToScore: 0
podInitialBackoffSeconds: 1
podMaxBackoffSeconds: 10
profiles:
  - plugins:
      filter:
        enabled:
          - name: Scheduling-framework-example
            weight: 0
      score:
        enabled:
          - name: Scheduling-framework-example
            weight: 2
    schedulerName: Scheduling-framework-example
